### ISSUE TITLE
Would you please help find out which modules is the 'radam'?

### ISSUE THREAD

**Issue by CumtbMax** [swag-kaust/storseismic#1]
in 'nb1_pretraining.ipynb'-'Load required modules'-'from radam import RAdam'，would you please tell me what's the name of the module? I need to install it by pip or conda. Thank you very much!

**Comment by randyharsuko** [comment]
Hi, thank you for pointing this out.
You can install this package directly from the repo () through pip by using:
```
pip install git+https://github.com/LiyuanLucasLiu/RAdam
```

I have also updated the README.md to include the installation instruction.

**Comment by CumtbMax** [comment]
thank you for your reply! I'm trying to reproduce this program, I hope it runs successfully on my MacBook, there's so much problems to be solved since I'm not very familiar with Python. Thank u!
